(() => {
  'use strict';
  const data = window.RADAR_DATA || {};
  const runs = Array.isArray(data.runs) ? data.runs : [];
  const $ = s => document.querySelector(s);
  const array = a => Array.isArray(a) ? a : [];
  const str = v => v == null || v === '' ? '未披露' : String(v);
  const el = (tag, text, cls) => { const n = document.createElement(tag); if (text != null) n.textContent = String(text); if (cls) n.className = cls; return n; };
  const safeLink = (url, text, cls = 'source-link') => { try { const u = new URL(url); if (!['http:', 'https:'].includes(u.protocol)) return el('span', text + '（链接未提供）', 'muted'); const a = el('a', text, cls); a.href = u.href; a.target = '_blank'; a.rel = 'noopener noreferrer'; return a; } catch { return el('span', text + '（链接未提供）', 'muted'); } };
  const unique = list => { const map = new Map(); for (const p of list) { const key = p.id || [p.number, p.buyer, p.title].join('|'); if (!map.has(key)) map.set(key, p); } return [...map.values()]; };
  const archive = unique(Array.isArray(data.archiveProjects) ? data.archiveProjects : [...runs].sort((a,b) => String(b.executedAt || '').localeCompare(String(a.executedAt || ''))).flatMap(r => array(r.projects)));
  let run = runs.find(r => r.id === data.defaultRunId) || runs[0] || { projects: [], coverage: {} };
  let scope = 'week';
  let currentProjects = [];
  let filtered = [];
  let activeView = 'overview';
  const dates = p => [p.publishedAt, ...array(p.events).map(e => e.publishedAt)].filter(Boolean).map(v => String(v).slice(0, 10));
  function scopeProjects() { if (scope === 'undated') return archive.filter(p=>!dates(p).length); if (scope === 'run') return unique(array(run.projects)); const range = scope === 'week' ? data.weekRange : data.yearRange; if (!range?.start || !range?.end) return []; return archive.filter(p => dates(p).some(d => d >= range.start.slice(0, 10) && d <= range.end.slice(0, 10))); }
  function empty(target, title, note) { const d = el('div', null, 'empty'); d.append(el('strong', title), el('span', note)); target.append(d); }
  const num = n => new Intl.NumberFormat('zh-CN', { maximumFractionDigits: 2 }).format(n);
  function amountNumber(a) { if (a.value === null || a.value === undefined || a.value === '') return null; const n = Number(a.value); if (!Number.isFinite(n)) return null; if (a.currency && !['CNY', 'RMB', '人民币', '元', '万元'].includes(a.currency)) return null; return a.currency === '万元' ? n : n / 10000; }
  function amountText(p) { const values = array(p.amounts).map(a => { const n = amountNumber(a); return n === null ? (a.raw ? str(a.type) + ' ' + a.raw : null) : str(a.type) + ' ' + num(n) + ' 万元'; }).filter(Boolean); return values.length ? values.join(' / ') : p.sourceQuality==='正文已取得'?'未提取到金额':'金额未取得'; }
  const amountScopeText = p => { if(p.amountScope) return p.amountScope; if(p.amountEligible === false) return '金额口径待核验，不纳入汇总'; const ambiguous = [/预算/, /限价|最高/, /成交|中标/].some(m => new Set(array(p.amounts).filter(a => m.test(a.type || '') && amountNumber(a) !== null).map(amountNumber)).size > 1); return ambiguous ? '同类金额存在多个值，该类不纳入汇总' : '以公告披露口径为准'; };
  const gapCount = p => array(p.gaps).filter(g => !['已补齐', 'resolved', 'complete', 'completed'].includes(g.status)).length;
  function metric(target, label, value, note) { const d = el('div', null, 'metric'); d.append(el('div', label, 'metric-label'), el('div', value, 'metric-value'), el('div', note, 'metric-note')); target.append(d); }
  function renderSummary() {
    const root = $('#metrics'); root.replaceChildren();
    const education = currentProjects.filter(p => ['教育核心', '教育相关'].includes(p.category)).length;
    metric(root, '项目及待核验线索', num(currentProjects.length), '正文已取得 ' + currentProjects.filter(p => p.sourceQuality === '正文已取得').length + ' / 待核验 ' + currentProjects.filter(p => p.sourceQuality !== '正文已取得').length + ' · 教育类 ' + education);
    const amountBox = el('div', null, 'metric amount-metric'); amountBox.append(el('div', '已披露金额 / 万元', 'metric-label'));
    for (const [label, matcher] of [['预算', /预算/], ['限价', /限价|最高/], ['成交', /成交|中标/]]) {
      let total = 0, count = 0;
      for (const p of currentProjects) { if(p.sourceQuality !== '正文已取得' || p.amountEligible === false) continue; const values = [...new Set(array(p.amounts).filter(a => matcher.test(a.type || '') && amountNumber(a) !== null).map(amountNumber))]; if (values.length === 1) { total += values[0]; count++; } }
      const line = el('div', null, 'amount-line'); line.append(el('span', label), el('strong', count ? num(total) : '未披露')); amountBox.append(line);
    }
    const disclosed = currentProjects.filter(p => p.sourceQuality === '正文已取得' && p.amountEligible !== false && array(p.amounts).some(a => amountNumber(a) !== null)).length;
    amountBox.append(el('div', '已取正文金额披露率 ' + disclosed + '/' + currentProjects.length + ' · 各口径不合计', 'metric-note')); root.append(amountBox);
    metric(root, '采购单位', num(new Set(currentProjects.map(p => p.buyer).filter(Boolean)).size), '按已披露采购单位名称去重');
    metric(root, '待补信息项目', num(currentProjects.filter(p => gapCount(p) || p.category === '待核验').length), '缺口与分类候选待复核');
    const regions = new Map(); currentProjects.forEach(p => { const r = p.province || '地区未披露'; regions.set(r, (regions.get(r) || 0) + 1); });
    const regionBox = $('#region-distribution'); regionBox.replaceChildren(el('span', '地区分布', 'region-label'));
    if (!regions.size) regionBox.append(el('span', '当前范围暂无可统计项目', 'muted'));
    [...regions].sort((a, b) => b[1] - a[1]).forEach(([r, n]) => { const chip = el('span', null, 'region-chip'); chip.append(el('span', r), el('b', n)); regionBox.append(chip); });
    const overview = $('#overview-projects'); overview.replaceChildren();
    if (!currentProjects.length) empty(overview, '这个观察范围，暂无项目。', scope === 'week' ? '本周没有已入库公告；可切换“近一年”或“本次试跑”查看已有记录。' : '当前没有符合日期范围的项目记录。');
    currentProjects.slice(0, 5).forEach((p, i) => overview.append(projectRow(p, i)));
  }
  function projectRow(p, i) { const row = el('article', null, 'project-row'); row.dataset.projectId = p.id || ''; row.append(el('span', String(i + 1).padStart(2, '0'), 'project-index')); const body = el('div'); const flags = el('div', null, 'row-flags'); flags.append(el('span', p.category || '待核验', 'tag')); flags.append(el('span', p.sourceQuality || '来源待核验', 'source-quality')); if (gapCount(p)) flags.append(el('span', gapCount(p) + ' 项证据待补', 'gap-mark')); body.append(flags); const title = el('button', p.title || '未命名项目', 'project-title'); title.addEventListener('click', () => showProject(p)); body.append(title); const meta = el('div', null, 'project-meta'); meta.append(el('span', str(p.buyer)), el('span', str(p.province)), el('span', '发布 ' + str(p.publishedAt))); body.append(meta); row.append(body); const finance = el('div', null, 'project-finance'); finance.append(el('strong', amountText(p)), el('small', amountScopeText(p))); row.append(finance); const arrow = el('button', '↗', 'row-arrow'); arrow.setAttribute('aria-label', '查看 ' + (p.title || '项目') + ' 的证据详情'); arrow.addEventListener('click', () => showProject(p)); row.append(arrow); return row; }
  function renderMatchFilters() {
    for (const [id, field, label] of [['keyword-filter','matchedTerms','全部命中词'],['point-filter','matchPoints','全部对位点']]) {
      const select = $('#'+id), selected = select.value, counts = new Map();
      currentProjects.forEach(p => array(p[field]).forEach(v => counts.set(v,(counts.get(v)||0)+1)));
      select.replaceChildren(); const all = el('option',label); all.value='all'; select.append(all);
      [...counts].sort((a,b)=>b[1]-a[1] || a[0].localeCompare(b[0],'zh-CN')).forEach(([value,n]) => { const opt=el('option',value+' · '+n);opt.value=value;select.append(opt); });
      select.value = counts.has(selected) ? selected : 'all';
    }
  }
  function renderProjects() {
    const q=$('#project-search').value.trim().toLocaleLowerCase(), category=$('#category-filter').value, term=$('#keyword-filter').value, point=$('#point-filter').value, quality=$('#quality-filter').value;
    filtered=currentProjects.filter(p => (category==='all'||p.category===category) && (term==='all'||array(p.matchedTerms).includes(term)) && (point==='all'||array(p.matchPoints).includes(point)) && (quality==='all'||p.sourceQuality===quality) && (!q||[p.title,p.buyer,p.number,p.province,...array(p.winners).map(x=>x.name),...array(p.matchedTerms),...array(p.matchPoints),...array(p.products).flatMap(x=>[x.name,x.text]),...array(p.parameters).map(x=>x.text)].filter(Boolean).join(' ').toLocaleLowerCase().includes(q)));
    $('#project-count').textContent='当前观察范围 · '+filtered.length+' 条 · 正文已取得 '+filtered.filter(p=>p.sourceQuality==='正文已取得').length;
    const root=$('#projects-list'); root.replaceChildren(); if(!filtered.length)return empty(root,'暂无匹配项目','请调整观察范围、命中词、对位点或分类。');
    const wrap=el('div',null,'table-wrap');wrap.tabIndex=0;wrap.setAttribute('aria-label','项目汇总表，可横向滚动');
    const table=el('table',null,'project-table'),head=el('thead'),tr=el('tr');
    ['项目名称 / 分类','金额','采购单位','采购时间','中标单位','数据来源','命中词 / 对位点','来源网站链接','主体性质 / 省份','响应截止','开标时间','正文与详情'].forEach(t=>{const th=el('th',t);th.scope='col';tr.append(th)});head.append(tr);table.append(head);
    const tbody=el('tbody');
    filtered.forEach(p=>{
      const row=el('tr');row.dataset.projectId=p.id||'';
      const title=el('td');title.append(safeLink(p.sourceUrl,p.title||'未命名项目','table-project-link'),el('span',(p.category||'待核验')+' · '+(p.sourceQuality||'来源待核验'),'table-category'));row.append(title);
      const amount=el('td');amount.append(el('div',amountText(p)),el('small',amountScopeText(p),'muted'));row.append(amount);
      row.append(el('td',p.buyer||'未取得'));
      const time=el('td');time.append(el('div',p.procurementTime?.value||p.publishedAt||'未取得'),el('small',p.procurementTime?.label||'公告发布','muted'));row.append(time);
      const award=el('td');award.append(el('div',array(p.winners).length?[...new Set(p.winners.map(w=>w.name))].join('；'):'未取得中标信息'));if(array(p.winners).length)award.append(el('small','正文提取，按各公告复核','muted'));row.append(award);
      const source=el('td');source.append(el('div',array(p.sourceNames).join('、')||'来源待核验'),el('small',p.sourceQuality||'来源待核验','muted'));row.append(source);
      const matches=el('td',null,'match-cell'),chips=el('div',null,'match-chips');array(p.matchedTerms).slice(0,5).forEach(t=>{const chip=el('button',t,'match-chip');chip.title='筛选命中词：'+t;chip.addEventListener('click',()=>{$('#keyword-filter').value=t;renderProjects()});chips.append(chip)});matches.append(chips);if(array(p.matchedTerms).length>5)matches.append(el('small','另 '+(p.matchedTerms.length-5)+' 个词，见详情','muted'));matches.append(el('div',array(p.matchPoints).join(' · ')||'词库未命中，待复核','match-points'));row.append(matches);
      const links=el('td');(array(p.sourceLinks).length?p.sourceLinks:[{url:p.sourceUrl,name:'来源网站'}]).slice(0,3).forEach(x=>{const line=el('div');line.append(safeLink(x.url,x.name+' ↗'));links.append(line)});row.append(links);
      row.append(el('td',[p.buyerType||'未识别',p.province||'未披露'].join(' / ')));[p.deadline,p.openingAt].forEach(v=>row.append(el('td',v||'未取得')));
      const detail=el('td'),btn=el('button','详情 ↗','detail-button');btn.addEventListener('click',()=>showProject(p));btn.setAttribute('aria-label','查看 '+p.title+' 的详情');detail.append(btn,el('small',array(p.fullTexts).length+' 份已取正文 / 附件','table-category'));row.append(detail);tbody.append(row);
    });table.append(tbody);wrap.append(table);root.append(wrap);
  }
  function renderCoverage() { const c = run.coverage || {}; const root = $('#coverage-summary'); root.replaceChildren(); const value = k => Number.isFinite(Number(c[k])) && c[k] != null ? Number(c[k]) : null; const planned = value('planned'), executed = value('executed'), failed = value('failed'); metric(root, '计划任务', planned ?? '未记录', '当前运行记录'); metric(root, '已执行', executed ?? '未记录', '包括执行失败的任务'); metric(root, '成功完成', executed != null && failed != null ? Math.max(0, executed - failed) : '未记录', '已执行减去失败'); metric(root, '未执行', value('unexecuted') ?? '未记录', '尚未发起的计划任务'); $('#coverage-note').textContent = planned === 0 ? '本轮仅补抓详情 / 未执行新发现。此记录不计算任务覆盖率。' : planned > 0 ? '本轮执行 ' + (executed ?? '未记录') + ' / ' + planned + ' 项计划任务，失败 ' + (failed ?? '未记录') + ' 项。全国查询计划不等于全网覆盖。' : '当前运行记录未提供任务覆盖数据，不能据此判断采集范围。'; const table = $('#coverage-table'); table.replaceChildren(); array(c.byRegion).forEach(r => { const row = el('tr'); [r.region, r.planned, r.executed, r.failed, r.unexecuted].forEach(v => row.append(el('td', str(v)))); table.append(row); }); if (!array(c.byRegion).length) { const row = el('tr'), td = el('td', '暂无地区任务明细', 'muted'); td.colSpan = 5; row.append(td); table.append(row); } }
  function detailSection(root, title, items, render) { const section = el('section', null, 'detail-section'); section.append(el('h3', title)); if (!items.length) section.append(el('p', '暂未提取到可核验信息。', 'muted')); items.forEach(item => { const card = el('article', null, 'evidence-item'); render(card, item); section.append(card); }); root.append(section); }
  function showProject(p) { const root = $('#dialog-content'); root.replaceChildren(); root.append(el('h2', p.title || '未命名项目', 'dialog-title')); root.lastChild.id = 'dialog-title'; root.append(el('span', p.category || '待核验', 'tag')); const meta = el('dl', null, 'detail-meta'); for (const [k,v] of [['采购单位', p.buyer], ['采购时间', (p.procurementTime?.value||'未取得')+'（'+(p.procurementTime?.label||'公告发布')+'）'], ['中标单位', array(p.winners).map(w=>w.name).join('；')||'未取得中标信息'], ['数据来源', array(p.sourceNames).join('、')], ['主体性质 / 省份', [p.buyerType || '未知', p.province || '未知'].join(' / ')], ['项目编号', p.number], ['发布日期', p.publishedAt], ['响应截止', p.deadline], ['开标时间', p.openingAt], ['日期依据',p.dateEvidence], ['来源质量', p.sourceQuality], ['正文读取方式',p.fetchMode], ['项目状态', p.status], ['详情状态', p.detailStatus], ['金额', amountText(p)], ['金额口径', amountScopeText(p)]]) { const pair = el('div'); pair.append(el('dt', k), el('dd', str(v))); meta.append(pair); } root.append(meta, safeLink(p.sourceUrl, '打开原始公告 ↗'));
    detailSection(root, '发布源头与附件追溯', array(p.sourceTrace), (card,item)=>{card.append(el('strong',item.kind+' · '+item.status),safeLink(item.url,' '+item.label+' ↗'))});
    detailSection(root, '命中词 / 对位点 · '+(p.keywordVersion||'待更新'), array(p.matchEvidence), (card,item)=>{card.append(el('strong',item.term+' · '+item.point),el('p',item.text),el('small',item.field+' / '+item.locator,'muted'),safeLink(item.url,' 查看命中原文 ↗'))});
    const bodies=el('section',null,'detail-section');bodies.append(el('h3','已取得的公告正文与公开附件'),el('p','以下保留已读取文本。公告正文与完整采购文件分别取证，扫描图片或未下载附件仍需补齐。','muted'));
    if(!array(p.fullTexts).length)bodies.append(el('p','正文尚未取得，当前仅有线索。','muted'));
    array(p.fullTexts).forEach(item=>{const box=el('details',null,'fulltext-item'),summary=el('summary',item.kind+' · '+item.title+' · '+num(item.characters)+' 字符'),content=el('div');box.append(summary,content);let loaded=false;box.addEventListener('toggle',async()=>{if(!box.open||loaded)return;loaded=true;content.replaceChildren(el('p','正在读取保存的正文…'));try{if(!/^bodies\/[a-f0-9]{64}\.json$/.test(item.path))throw Error('invalid_path');const response=await fetch(item.path);if(!response.ok)throw Error('HTTP '+response.status);const body=await response.json();content.replaceChildren(el('p','读取时间：'+str(body.readAt),'muted'),safeLink(body.url,'打开来源网站 ↗'),el('pre',body.text,'fulltext-content'));}catch{loaded=false;content.replaceChildren(el('p','保存正文暂时未能加载，请稍后重试。','muted'),safeLink(item.url,'打开来源网站 ↗'));}});bodies.append(box)});root.append(bodies);
    detailSection(root, '01 / 产品与采购内容', array(p.products), (card, item) => { if (item.name) card.append(el('strong', item.name)); card.append(el('p', item.text || '未提供正文')); const loc = el('div', null, 'evidence-locator'); loc.append(el('span', '证据定位：' + str(item.locator)), safeLink(item.url, '查看证据原文 ↗')); card.append(loc); });
    detailSection(root, '02 / 技术参数', array(p.parameters), (card, item) => { card.append(el('p', item.text || '未提供正文')); const loc = el('div', null, 'evidence-locator'); loc.append(el('span', '证据定位：' + str(item.locator)), safeLink(item.url, '查看参数原文 ↗')); card.append(loc); });
    detailSection(root, '03 / 公告事件', array(p.events), (card, item) => { card.append(el('strong', item.title || item.type || '公告事件'), el('p', '类型：' + str(item.type) + ' · 发布：' + str(item.publishedAt) + ' · 截止：' + str(item.deadline)), safeLink(item.url, '查看事件原文 ↗')); });
    detailSection(root, '04 / 信息缺口', array(p.gaps), (card, item) => { card.append(el('strong', str(item.name) + ' · ' + str(item.status)), el('p', str(item.reason))); if (item.url) card.append(safeLink(item.url, '查看相关来源 ↗')); });
    $('#project-dialog').showModal(); $('#close-dialog').focus(); }
  function render() { currentProjects = scopeProjects().sort((a,b) => String(b.publishedAt || '').localeCompare(String(a.publishedAt || ''))); const range = scope === 'week' ? data.weekRange : scope === 'year' ? data.yearRange : run; const label = scope === 'week' ? '本周' : scope === 'year' ? '近一年' : scope === 'undated' ? '日期待核验' : '本次试跑'; $('#run-period').textContent = label + ' / ' + (range?.start && range?.end ? range.start + ' — ' + range.end : '日期范围未提供'); $('#run-status').textContent = scope === 'run' ? run.status || '状态未提供' : '按公告日期观察'; $('#scope-caption').textContent = scope === 'run' ? '仅当前选中的运行记录' : '按归档项目的公告事件日期筛选'; renderSummary(); renderMatchFilters(); renderProjects(); renderCoverage(); const ac = data.archiveCoverage; const note = $('#archive-coverage'); note.replaceChildren(); if (ac) { note.append(el('strong', '年度回溯范围'), el('p', '查询 ' + str(ac.queries) + ' · 候选 ' + str(ac.candidates) + ' · 已抓取 ' + str(ac.fetched) + ' · 读取失败 ' + str(ac.failed) + ' · 待处理 ' + str(ac.pending) + ' · 非采购排除 ' + str(ac.excluded) + ' · 有记录月份 ' + (Array.isArray(ac.monthsCovered) ? ac.monthsCovered.join('、') : str(ac.monthsCovered))), el('p', ac.limitation || '年度回溯记录不代表全网完整覆盖。')); } }
  function navigate(view) { activeView = view; document.querySelectorAll('.view').forEach(n => n.hidden = n.id !== 'view-' + view); document.querySelectorAll('.nav-item').forEach(n => { const active = n.dataset.view === view; n.classList.toggle('active', active); if(active) n.setAttribute('aria-current', 'page'); else n.removeAttribute('aria-current'); }); if(view === 'projects') { const bar = $('.scope-bar'); $('#view-projects .compact-intro').after(bar); } else if(view === 'overview') $('#metrics').before($('.scope-bar')); }
  $('.brand').addEventListener('click', e => { e.preventDefault(); navigate('overview'); });
  runs.forEach(r => { const opt = el('option', r.label || r.id); opt.value = r.id; $('#run-select').append(opt); }); if (!runs.length) $('#run-select').append(el('option', '暂无运行记录')); $('#run-select').value = run.id || ''; $('#run-select').addEventListener('change', e => { run = runs.find(r => r.id === e.target.value) || run; render(); }); $('#scope-select').addEventListener('change', e => { scope = e.target.value; render(); }); document.querySelectorAll('[data-view]').forEach(n => n.addEventListener('click', () => navigate(n.dataset.view))); document.querySelectorAll('[data-go]').forEach(n => n.addEventListener('click', () => navigate(n.dataset.go))); $('#project-search').addEventListener('input', renderProjects); $('#category-filter').addEventListener('change', renderProjects); ['keyword-filter','point-filter','quality-filter'].forEach(id=>$('#'+id).addEventListener('change',renderProjects)); $('#close-dialog').addEventListener('click', () => $('#project-dialog').close()); $('#project-dialog').addEventListener('click', e => { if(e.target === e.currentTarget) { const r = e.currentTarget.getBoundingClientRect(); if(e.clientX < r.left || e.clientX > r.right || e.clientY < r.top || e.clientY > r.bottom) e.currentTarget.close(); } }); $('#export-json').addEventListener('click', () => { const blob = new Blob([JSON.stringify({title:data.title || '心育采购观察', scope, runId:scope === 'run' ? run.id : null, exportedAt:new Date().toISOString(), projects:filtered}, null, 2)], {type:'application/json;charset=utf-8'}); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href=url; a.download='心育采购观察-'+scope+'.json'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }); $('#build-time').textContent = data.builtAt ? '数据更新 ' + data.builtAt : '尚未载入数据'; render();
})();
